language: c

os:
  - osx
  - linux

env: FF_ROOT=$TRAVIS_BUILD_DIR FF_VERSION=3.4.2 FF_CPU=2

cache:
  directories:
    - $FF_ROOT/cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q && sudo apt-get install -y gcc-4.8; fi

script: ./build.sh
